apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BlackRock2308/django-devops-dic3.git
    path: kubernetes_manifest   # Directory containing the "App of Apps" configuration
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-django
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BlackRock2308/django-devops-dic3.git
    path: k8s-manifest
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

